name: display of FTP
on:
  push:
    -branches:
    - main
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Deploy app
  
  uses: SamKirkLand/FTP-Deploy-Action@v4.3.4
  with:
  server: "s1.ct8.pl"
  server-dir: "./public_html/ "
  username: ${{secrets.FTP_USERNAME}}
  password: ${{secrets.FTP_PASSWORD}}
